name: Convert ODT to PDF and attach to release

on:
  release:
    types: [created]

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install LibreOffice
      run: sudo apt-get update && sudo apt-get install -y libreoffice

    - name: Convert ODT to PDF
      run: find . -name "*.odt" -exec libreoffice --headless --convert-to pdf {} \;

    - name: List generated PDFs
      id: list_pdfs
      run: |
        pdf_files=$(find . -name "*.pdf" | tr '\n' ' ')
        echo "pdf_files=$pdf_files" >> $GITHUB_ENV
        echo "::set-output name=pdf_files::$pdf_files"

    - name: Upload PDF to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.list_pdfs.outputs.pdf_files }}
        asset_name: ${{ steps.list_pdfs.outputs.pdf_files | basename }}
        asset_content_type: application/pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
